const characters = [
{
Name:"Mario of SMB1" ,
Img :["characters/Mario-sprite.png","characters/Luigi-sprite.png","characters/GoldMario-sprite.png","characters/GreenLuigi-sprite.png"],
Grid:[/*width*/ 32,/*height*/32,/*static*/0,/*walk*/3,/*run*/0,/*brek*/4,
/*jumpUP*/1,/*jumpDOWN*/1,/*jump+run*/0,/*simw*/3,/*death*/0 ],
width:24,
height:32,
WNEGA:-4,
HNEGA:0,
WinSound: "SoundEfects/WinSMB1.mp3",
DeathSound:"SoundEfects/DeathSMB1.mp3",
GameOverSound: "SoundEfects/Game OverSMB1.mp3"

},
{
Name:"New Mario Characters" ,
Img :[
"characters/NewMario.png","characters/NewLuigi.png",
"characters/NewPeach.png","characters/NewDaisy.png",
"characters/NewToad.png","characters/NewToaded.png",
"characters/NewWario.png","characters/NewWaluigi.png",
],
Grid:[/*width*/ 48,/*height*/48,/*static*/1,/*walk*/3,/*run*/2,/*brek*/7,
/*jumpUP*/1,/*jumpDOWN*/1,/*jump+run*/0,/*simw*/6,/*death*/0 ],
width:24,
height:32,
WNEGA:-12,
HNEGA:-16,
WinSound: "SoundEfects/WinNew.mp3",
DeathSound:"SoundEfects/DeathNew.mp3",
GameOverSound: "SoundEfects/Game OverNew.mp3"
},
{
Name:"Enemies and objects" ,
Img :["characters/QuestionBlock.png","characters/BoingBlock.png","characters/Resorte.png","characters/Resorte2.png"],
Grid:[/*width*/ 48,/*height*/48,/*static*/1,/*walk*/3,/*run*/2,/*brek*/7,
/*jumpUP*/1,/*jumpDOWN*/1,/*jump+run*/0,/*simw*/6,/*death*/0 ],
width:24,
height:32,
WNEGA:-12,
HNEGA:-16,
WinSound: "SoundEfects/WinNew.mp3",
DeathSound:"SoundEfects/DeathNew.mp3",
GameOverSound: "SoundEfects/Game OverNew.mp3"
},
{
Name:"Super Mario of SMB1" ,
Img :[
"characters/BigMario-sprite.png",
"characters/BigLuigi-sprite.png",
"characters/BigToad-sprite.png",
"characters/Peach-sprite.png",
"characters/MarioFlaco-sprite.png",],
Grid:[/*width*/ 32,/*height*/64,/*static*/0,/*walk*/3,/*run*/0,/*brek*/4,
/*jumpUP*/1,/*jumpDOWN*/1,/*jump+run*/0,/*simw*/3,/*death*/0 ],
width:32,
height:64,
WNEGA:0,
HNEGA:0,
WinSound: "SoundEfects/WinSMB1.mp3",
DeathSound:"SoundEfects/DeathSMB1.mp3",
GameOverSound: "SoundEfects/Game OverSMB1.mp3"
},
{
Name:"Mario Maker characters of SMB1" ,
Img :["characters/Toadet-sprite.png","characters/KingDeDeDe.png","characters/SMB1Bowser-Sprite.png"],
Grid:[/*width*/ 64,/*height*/64,/*static*/0,/*walk*/3,/*run*/0,/*brek*/4,
/*jumpUP*/1,/*jumpDOWN*/1,/*jump+run*/0,/*simw*/6,/*death*/0 ],
width:32,
height:64,
WNEGA:-16,
HNEGA:0,
WinSound: "SoundEfects/WinSMB1.mp3",
DeathSound:"SoundEfects/DeathSMB1.mp3",
GameOverSound: "SoundEfects/Game OverSMB1.mp3"
},
{
Name:"Mario Maker costumes of SMB1" ,
Img :["characters/BabyMario-sprite.png","characters/Bowser-sprites.png"],
Grid:[/*width*/ 48,/*height*/48,/*static*/1,/*walk*/3,/*run*/2,/*brek*/7,
/*jumpUP*/1,/*jumpDOWN*/1,/*jump+run*/0,/*simw*/3,/*death*/0 ],
width:32,
height:32,
WNEGA:-8,
HNEGA:-16,
},
{
Name:"Mario of SMB3" ,
Img :["characters/Mario3.png","characters/Luigi3.png","characters/MarioRaccon.png","characters/MarioTanoky.png",
"characters/MarioFrog.png","characters/MarioHammerBros.png","characters/Toad3.png","characters/Toaded3.png"],
Grid:[64,64,/*static*/0,/*walk*/2,/*run*/3,/*brek*/6,/*jumpUP*/1,/*jumpDOWN*/1,/*jump+run*/2,/*swim*/4,/*death*/0],
width:32,
height:54,
WNEGA:-16,
HNEGA:-10,
DeathSound:"SoundEfects/DeathSMB3.mp3",
GameOverSound: "SoundEfects/Game OverSMB3.mp3"
},
{
Name:"Mario of SMW" ,
Img :["characters/Mario-SMW.png"],
Grid:[32,48,/*static*/0,/*walk*/1,/*run*/2,/*brek*/4,/*jumpUP*/1,/*jumpDOWN*/1,/*jump+run*/2,/*swim*/3,/*death*/1],
width:24,
height:32,
WNEGA:-4,
HNEGA:-14,
WinSound: "SoundEfects/WinSMW.mp3",
DeathSound:"SoundEfects/DeathSMW.mp3",
GameOverSound: "SoundEfects/Game OverSMW.mp3"
},
{
Name:"JUMP-MAN" ,
Img :["characters/Jump_Man.png"],
Grid:[32,32,/*static*/0,/*walk*/2,/*run*/0,/*brek*/3,/*jumpUP*/1,/*jumpDOWN*/0,/*jump+run*/0,/*swim*/6,/*death*/3],
width:24,
height:32,
WNEGA:-4,
HNEGA:0,
DeathSound:"SoundEfects/DeathDKA.mp3",
WinSound: "SoundEfects/WinDKA.mp3",
},
{
Name:"SirHartur" ,
Img :["characters/SirArthur.png","characters/SirArthurUndresed.png"],
Grid:[64,64,/*static*/1,/*walk*/4,/*run*/3,/*brek*/0,/*jumpUP*/1,/*jumpDOWN*/1,/*jump+run*/0,/*simw*/6,/*death*/0 ],
width:32,
height:64,
WNEGA:-16,
HNEGA:0,
WinSound: "SoundEfects/WinArthur.mp3",
DeathSound:"SoundEfects/DeathArthur.mp3",
GameOverSound: "SoundEfects/Game OverArthur.mp3",
},
//{
//Name:"Metroid" ,
//Img :["characters/SamusAran2.png","characters/SamusAranSuitless2.png"],
//Grid:[64,64,/*static*/1,/*walk*/3,/*run*/2,/*brek*/0,/*jumpUP*/4,/*jumpDOWN*/0,/*jump+run*/4,/*simw*/4,/*death*/0 ],
//width:32,
//height:64,
//WNEGA:-16,
//HNEGA:0,
//},
{
Name:"Sonic the hedghog" ,
Img :["characters/SonicSprite.png","characters/KnucklesSprite.png"],
Grid:[59,59,/*static*/1,/*walk*/8,/*run*/3,/*brek*/17,/*jumpUP*/5,/*jumpDOWN*/0,/*jump+run*/0,/*simw*/4,/*death*/0 ],
width:24,
height:40,
WNEGA:-18,
HNEGA:-11,
WinSound: "SoundEfects/WinSONIC.mp3",
DeathSound:"SoundEfects/DeathSonic.wav",
GameOverSound: "SoundEfects/Game OverSONIC.mp3",
},
]