MusicList = [
 {"Crs":"Music/smooth jazz.mp3", "Name":"smooth jazz",},
  {"Crs":"Music/Circus Charlie Jump Through the Wheel of Fire.mp3", "Name":"Circus Charlie Theme",},
   {"Crs":"Music/Circus Charlie Ropewalking.mp3", "Name":"Circus Charlie Ropewalking",},
 {"Crs":"Music/Super Mario Bros Ground Theme.mp3", "Name":"Super Mario Bros Ground Theme.mp3",},
 {"Crs":"Music/Super Mario Bros  Underground Theme.mp3", "Name":"Super Mario Bros  Underground Theme",},
 {"Crs":"Music/Super Mario Bros Ground Theme (Remix).mp3", "Name":"Super Mario Bros Ground Theme (Remix)",},
 {"Crs":"Music/Super Mario Bros  3 Athletic.mp3", "Name":"Super Mario Bros  3 Athletic",},
 {"Crs":"Music/Super Mario World Athletic.mp3", "Name":"Super Mario World Athletic",},
 {"Crs":"Music/Super Mario World Fortress.mp3", "Name":"Super Mario World Fortress",},
 {"Crs":"Music/Super Mario 64 Main Theme.mp3" , "Name":"Super Mario 64 Main Theme",},
 {"Crs":"Music/Super Mario 64 Dire, Dire Docks.mp3" , "Name":"Super Mario 64 Dire, Dire Docks",},
 {"Crs":"Music/Super Mario 64 Lethal Lava Land.mp3", "Name":"Super Mario 64 Lethal Lava Land",},
 {"Crs":"Music/Super Mario 3D Land Beach Theme.mp3", "Name":"Super Mario 3D Land Beach Theme",},
 {"Crs":"Music/Kirby Super Star Green Greens.mp3", "Name":"Kirby Super Star Green Greens",},
 {"Crs":"Music/Kirby Super Star Save Hut.mp3", "Name":"Kirby Super Star Save Hut",},
 {"Crs":"Music/Kirby Super Star King Dedede's Theme.mp3", "Name":"Kirby Super Star King Dedede's Theme",},
 {"Crs":"Music/Sonic The Hedghog Green Hill Zone (Remix).mp3", "Name":"Sonic The Hedghog Green Hill Zone (Remix)",},
 {"Crs":"Music/Donkey Kong Country DK Island Swing .mp3", "Name":"Donkey Kong Country DK Island Swing",},
 {"Crs":"Music/Donkey Kong Country Fear Factory.mp3", "Name":"Donkey Kong Country Fear Factory",},
 {"Crs":"Music/Doom At Doom's Gate.mp3", "Name":"Doom At Doom's Gate",},
 {"Crs":"Music/Doom 2 RunningFromEvil.mp3", "Name":"Doom 2 RunningFromEvil",},
]