MusicList = [
 {"Crs":"Music/smooth jazz.mp3", "Name":"smooth jazz",},
 {"Crs":"Music/Joakim Karud - Classic.mp3", "Name":"Joakim Karud - Classic",},
 {"Crs":"Music/Joakim Karud - Clouds.mp3", "Name":"Joakim Karud - Clouds",},
 {"Crs":"Music/Joakim Karud - Sunshine.mp3", "Name":"Joakim Karud - Sunshine",},
 {"Crs":"Music/Joakim Karud - Dreams.mp3", "Name":"Joakim Karud - Dreams",},
  {"Crs":"Music/Circus Charlie Jump Through the Wheel of Fire.mp3", "Name":"Circus Charlie Theme",},
   {"Crs":"Music/Circus Charlie Ropewalking.mp3", "Name":"Circus Charlie Ropewalking",},
 {"Crs":"Music/Super Mario Bros Ground Theme.mp3", "Name":"Super Mario Bros Ground Theme.mp3",},
 {"Crs":"Music/Super Mario Bros  Underground Theme.mp3", "Name":"Super Mario Bros  Underground Theme",},
 {"Crs":"Music/Super Mario Bros Ground Theme (Remix).mp3", "Name":"Super Mario Bros Ground Theme (Remix)",},
 {"Crs":"Music/Super Mario Bros  3 Athletic.mp3", "Name":"Super Mario Bros  3 Athletic",},
 {"Crs":"Music/Super Mario Land Birabuto Kingdom.mp3", "Name":"Super Mario Land Birabuto Kingdom",},
 {"Crs":"Music/Super Mario Land Muda Kingdom.mp3", "Name":"Super Mario Land Muda Kingdom",},
 {"Crs":"Music/Super Mario World Overworld.mp3", "Name":"Super Mario World Overworld",},
 {"Crs":"Music/Super Mario World Athletic.mp3", "Name":"Super Mario World Athletic",},
 {"Crs":"Music/Super Mario World Star Road.flac", "Name":"Super Mario World Star Road",},
 {"Crs":"Music/Super Mario World Fortress.mp3", "Name":"Super Mario World Fortress",},
 {"Crs":"Music/Super Mario 64 Main Theme.mp3" , "Name":"Super Mario 64 Main Theme",},
 {"Crs":"Music/Super Mario 64 Dire, Dire Docks.mp3" , "Name":"Super Mario 64 Dire, Dire Docks",},
 {"Crs":"Music/Super Mario 64 Lethal Lava Land.mp3", "Name":"Super Mario 64 Lethal Lava Land",},
 {"Crs":"Music/New Super Mario Bros Overworld.mp3", "Name":"New Super Mario Bros Overworld",},
 {"Crs":"Music/New Super Mario Bros Athletic.mp3", "Name":"New Super Mario Bros Athletic",},
 {"Crs":"Music/New Super Mario Bros The Plains.mp3", "Name":"New Super Mario Bros The Plains",},
 {"Crs":"Music/Super Mario 3D Land Beach Theme.mp3", "Name":"Super Mario 3D Land Beach Theme",},
 {"Crs":"Music/Kirby Super Star Green Greens.mp3", "Name":"Kirby Super Star Green Greens",},
 {"Crs":"Music/Kirby Super Star Save Hut.mp3", "Name":"Kirby Super Star Save Hut",},
 {"Crs":"Music/Kirby Super Star King Dedede's Theme.mp3", "Name":"Kirby Super Star King Dedede's Theme",},
 {"Crs":"Music/Sonic The Hedghog Green Hill Zone (Remix).mp3", "Name":"Sonic The Hedghog Green Hill Zone (Remix)",},
 {"Crs":"Music/Donkey Kong Country DK Island Swing .mp3", "Name":"DonkeyKong Country DK Island Swing",},
 {"Crs":"Music/Donkey Kong Country Fear Factory.mp3", "Name":"DonkeyKong Country Fear Factory",},
 {"Crs":"Music/Donkey Kong Country2  Snakey Chantey.mp3", "Name":"DonkeyKong Country2 Snakey Chantey",},
 {"Crs":"Music/Donkey Kong Country2 Forest Interlude.mp3", "Name":"DonkeyKong Country2 Forest Interlude",},
 {"Crs":"Music/Donkey Kong Country2 Stickerbush Symphony.mp3", "Name":"Donkey Kong Country2 Stickerbush",},
 {"Crs":"Music/Ghosts n Goblins Ground Theme (Remix).mp3", "Name":"Ghosts n Goblins Execution Grounds",},
 {"Crs":"Music/Doom At Doom's Gate.mp3", "Name":"Doom At Doom's Gate",},
 {"Crs":"Music/Doom 2 RunningFromEvil.mp3", "Name":"Doom 2 RunningFromEvil",},
]